name: pythondsminecraft
main: com.sbp.pythondsminecraft.pythondsminecraft
version : 2.1
description: Implementation for Minecraft Java server - Command Interface for programming with Python in Minecraft -  need to be use with with "mcse" (MineCraft SErver) python library
api-version: 1.15
startup: postworld
author: [Zhuowei, sbp]
website: http://pinet.rouviere.free.fr/description_mcse/index.html